name: "Run on PR Merge to Master"

on:
  pull_request:
    types:
      - closed

jobs:
  merge:
    uses: decaf-ts/reusable-actions/.github/workflows/release-on-merge-pr.yml@main
    secrets: inherit
