name: "Trivy Security Scan"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  trivy-scan:
    name: Trivy vuln scan
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    uses: decaf-ts/reusable-actions/.github/workflows/trivy-scan.yml@master
    with:
      scan-type: vuln
      severity: HIGH,CRITICAL
      exit-code: "0"
    secrets: inherit
